Repository cds-snc/covid-alert-server, pull requests merged in 2020-06, with the labels that each got.

#87 Small changes to Cloudfront settings
  config/terraform/aws/cloudfront.tf
Labels: network, security

#86 KMS implemented for CloudWatch log group
  config/terraform/aws/cloudwatch.tf
  config/terraform/aws/kms.tf
Labels: security

#85 Add VPC flow logging
  config/terraform/aws/vpc_flow_log.tf
Labels: infrastructure

#107 CODEOWNERS: CDS devs must review code changes
  .github/CODEOWNERS
Labels: security

#117 BVC 52 :: Extract last appended IP from X-Forwarded-For header
  pkg/server/keyclaim.go
Labels: security

#112 BVC-41 :: Fixes faulty bounds checking for keysRemaining in key upload
  pkg/persistence/queries.go
  pkg/server/upload.go
  test/lib/helper.rb
  test/upload_test.rb
Labels: security, server
